### ISSUE TITLE
Getting error when using tsd in node package 

### ISSUE THREAD

**Issue by bmperdue** [borisyankov/DefinitelyTyped#3570]
If I run: tsd query jquery -a install
 I get the following error. 
 tsd 0.5.7

-> an error occured!

Error: unexpected status code: 403 on: https://api.github.com/repos/borisyankov/DefinitelyTyped/branches/master
    at Request.<anonymous> (D:\home\data\monaco\home\npm\node_modules\tsd\build\api.js:4504:34)
    at Request.emit (events.js:95:17)
    at Request.onResponse (D:\home\data\monaco\home\npm\node_modules\tsd\node_modules\request\request.js:827:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
    at CleartextStream.Readable.read (_stream_readable.js:323:10)

**Comment by vvakame** [comment]
It is not DT repo issue.
please ask to tsd repo.
cc: @Bartvds
